source 'https://rubygems.org'

ruby '~> 3.0'

gem 'rails', '~> 7.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.0'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'
gem 'marcel', '~> 1.0'

group :development, :test do
  gem 'debug'
end
